// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQXPHHNgKdlCXtPpdXCoFgd7kCw7HTf8U',
    appId: '1:692577185240:web:4a0437920a1196c6bb16ad',
    messagingSenderId: '692577185240',
    projectId: 'apex-test-5ed98',
    authDomain: 'apex-test-5ed98.firebaseapp.com',
    storageBucket: 'apex-test-5ed98.firebasestorage.app',
    measurementId: 'G-QT38NNHXHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBade-JIQuIMruwSJQZ2KlUZ942LJ6sTn4',
    appId: '1:692577185240:android:4b362d5a4039558fbb16ad',
    messagingSenderId: '692577185240',
    projectId: 'apex-test-5ed98',
    storageBucket: 'apex-test-5ed98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4wNzrxgJX2q4JshbhbJV2-gqm9uJQ8bw',
    appId: '1:692577185240:ios:6bfc6527316848fcbb16ad',
    messagingSenderId: '692577185240',
    projectId: 'apex-test-5ed98',
    storageBucket: 'apex-test-5ed98.firebasestorage.app',
    iosBundleId: 'com.nerdybeast.apex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4wNzrxgJX2q4JshbhbJV2-gqm9uJQ8bw',
    appId: '1:692577185240:ios:6bfc6527316848fcbb16ad',
    messagingSenderId: '692577185240',
    projectId: 'apex-test-5ed98',
    storageBucket: 'apex-test-5ed98.firebasestorage.app',
    iosBundleId: 'com.nerdybeast.apex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQXPHHNgKdlCXtPpdXCoFgd7kCw7HTf8U',
    appId: '1:692577185240:web:7e162b3a336748dabb16ad',
    messagingSenderId: '692577185240',
    projectId: 'apex-test-5ed98',
    authDomain: 'apex-test-5ed98.firebaseapp.com',
    storageBucket: 'apex-test-5ed98.firebasestorage.app',
    measurementId: 'G-1MJ3248TPJ',
  );
}
